name: Release Container Image
run-name: Release new nodejs related container image to docker hub 🚀
on:
  push:
    paths:
      - node/**

jobs:
  release-pm2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      -
        name: Release nodejs PM2 widnyana/pm2:14-alpine
        uses: docker/build-push-action@v3
        with:
          context: ./node/pm2/14
          push: true
          tags: widnyana/pm2:14-alpine

      -
        name: Release nodejs PM2 widnyana/pm2:16-alpine
        uses: docker/build-push-action@v3
        with:
          context: ./node/pm2/16
          push: true
          tags: widnyana/pm2:16-alpine