name: Release Container Image
run-name: Release new container image to docker hub 🚀
on:
  push:
    branches:
      - master

jobs:
  docker-debian:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-builder/debian
        shell: bash
    steps:

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      -
        name: Release go-builder debian
        run: ./build.sh 
